/** Audit `action` qiymatlari — matn sifatida tarqalib ketmasligi uchun. */
export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: 'auth.login.success',
  LOGIN_FAILED: 'auth.login.failed',
  LOGIN_LOCKED: 'auth.login.locked',
  LOGOUT: 'auth.logout',
  TOKEN_REFRESH: 'auth.token.refresh',
  TOKEN_REUSE_DETECTED: 'auth.token.reuse_detected',
  ROLE_CHANGED: 'user.role.changed',
  MEDIA_UPLOADED: 'media.uploaded',
  MEDIA_DELETED: 'media.deleted',
  PRODUCT_CREATED: 'product.created',
  PRODUCT_UPDATED: 'product.updated',
  PRODUCT_DELETED: 'product.deleted',
  CATEGORY_CREATED: 'product.category.created',
  CATEGORY_UPDATED: 'product.category.updated',
  CONTENT_CREATED: 'content.created',
  CONTENT_UPDATED: 'content.updated',
  CONTENT_DELETED: 'content.deleted',
  SETTINGS_UPDATED: 'settings.updated',
  LEAD_STATUS_CHANGED: 'lead.status.changed',
  LEAD_ASSIGNED: 'lead.assigned',
  DEALER_REGISTERED: 'dealer.registered',
  DEALER_UPDATED: 'dealer.updated',
  DEALER_STATUS_CHANGED: 'dealer.status.changed',
  DEALER_TERMS_CHANGED: 'dealer.terms.changed',
  DEALER_ADDRESS_CREATED: 'dealer.address.created',
  DEALER_ADDRESS_UPDATED: 'dealer.address.updated',
  DEALER_ADDRESS_DELETED: 'dealer.address.deleted',
  DEALER_TIER_CHANGED: 'dealer.tier.changed',
  PRICE_RULE_CHANGED: 'pricing.rule.changed',
  ORDER_CREATED: 'order.created',
  ORDER_STATUS_CHANGED: 'order.status.changed',
  ORDER_NOTE_CHANGED: 'order.note.changed',
  WAREHOUSE_CHANGED: 'warehouse.changed',
  STOCK_MOVED: 'stock.moved',
  STOCK_ADJUSTED: 'stock.adjusted',
  STOCK_THRESHOLD_CHANGED: 'stock.threshold.changed',
  STOCK_RESERVED: 'stock.reserved',
  STOCK_RELEASED: 'stock.released',
  STOCK_FULFILLED: 'stock.fulfilled',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
